accounts/models.py
from datetime import datetime

from flask_login import UserMixin

from project_dataase.database import db


class User(UserMixin, db.Model):
    __tablename__ = "users"

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(255), index=True, unique=True, nullable=False)
    hashed_password = db.Column(db.String(255), unique=False, nullable=False)
    city = db.Column(db.String(255), unique=False, nullable=False)
    role = db.Column(db.Integer)

    def __repr__(self):
        return f"<User {self.username}>"


class Favorite(UserMixin, db.Model):
    __tablename__ = "Favorite"

    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    city_id = db.Column(db.Integer, db.ForeignKey('city.id'))
    date_add = db.Column(db.DateTime, default=datetime.now())

    def __repr__(self):
        return f"User:{self.user_id} -> City:{self.city_id}"

accounts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, validators, IntegerField, BooleanField


class RegistrationForm(FlaskForm):
    username = StringField('username', [
        validators.Length(min=1, max=255),
        validators.DataRequired()
    ])
    password = PasswordField('password', [validators.DataRequired(),
                                          validators.Length(min=1, max=255)
                                          ])
    city = StringField('city', [
        validators.Length(min=1, max=255),
        validators.DataRequired()
    ])
    repeat_password = PasswordField('repeat_password', [
        validators.DataRequired(),
        validators.Length(min=1, max=255)
    ])


class LoginForm(FlaskForm):
    username = StringField('username', [
        validators.Length(min=1, max=255),
        validators.DataRequired()
    ])
    password = PasswordField('password', [validators.DataRequired(),
                                          validators.Length(min=1, max=255)
                                          ])
    remember_me = BooleanField('remember_me')


class LoginFormWithoutPassword(FlaskForm):
    id = IntegerField('id', [
        validators.DataRequired()
    ])
    username = StringField('username', [
        validators.Length(min=1, max=255),
        validators.DataRequired()
    ])
    city = StringField('city', [
        validators.Length(min=1, max=255),
        validators.DataRequired()
    ])

accounts/controllers.py
from flask import request, redirect, url_for, flash, render_template, Blueprint, abort
from flask_login import login_user, login_required, logout_user, current_user
from werkzeug.security import generate_password_hash

from accounts.forms import RegistrationForm, LoginForm, LoginFormWithoutPassword
from accounts.login_manager import login_manager
from accounts.models import User
from accounts.services import find_by_username_and_password, NotFoundError, find_user_by_id, \
    find_user_by_username, find_by_id_username_city
from project_dataase.database import db

accounts_blueprint = Blueprint('accounts', __name__, template_folder='templates')


@accounts_blueprint.route('/register', methods=('POST', 'GET'))
def register():
    form: RegistrationForm = RegistrationForm(request.form)
    if request.method == 'POST':
        if form.validate_on_submit():
            try:
                if find_user_by_username(form.username.data):
                    flash('Аккаунт с таким Username уже существует')
                    return redirect(url_for('accounts.register'))
                user = User(username=form.username.data, hashed_password=generate_password_hash(form.password.data),
                            city=form.city.data, role='0')
                db.session.add(user)
                db.session.commit()
                login_user(user, remember=False)
                return redirect(url_for('company_management.main_page'))
            except TypeError as e:
                db.session.rollback()
                print('Ошибка добавления в БД')
        else:
            flash("Упс, ты не прошёл валидацию")
    return render_template('accounts/signup.html', form=form)


@accounts_blueprint.route('/login', methods=('GET', 'POST'))
def login():
    form: LoginForm = LoginForm(request.form)
    if request.method == 'POST' and form.validate_on_submit():
        try:
            user: User = find_by_username_and_password(form.username.data, form.password.data)
        except Exception as e:
            flash(str(e) or 'Unknown error')
            # save_username = form.username.data
            return redirect(url_for('accounts.login'))
        else:
            login_user(user, remember=form.remember_me.data)
            return redirect(url_for('company_management.main_page'))
    return render_template('accounts/login.html', form=form)


@accounts_blueprint.route("/oops", methods=["GET", "POST"])
def oops():
    form: LoginFormWithoutPassword = LoginFormWithoutPassword(request.form)
    if request.method == 'POST' and form.validate_on_submit():
        request_id: int = int(request.form['id'])
        request_username: str = request.form['username']
        request_city: str = request.form['city']
        try:
            user = find_by_id_username_city(user_id=form.id.data, username=form.username.data, city=form.city.data)
        except Exception as e:
            flash(str(e) or 'Unknown error')
            return redirect(url_for('accounts.oops'))
        else:
            login_user(user)
            return redirect(url_for('company_management.main_page'))
    return render_template('accounts/Oops!.html', form=form)


@accounts_blueprint.route("/logout", methods=["GET"])
@login_required
def logout():
    logout_user()
    return redirect(url_for('company_management.main_page'))


@accounts_blueprint.route("/user/<int:user_id>", methods=["GET", "POST"])
@login_required
def user_info(user_id: int):
    try:
        user: object = find_user_by_id(user_id)
        if user is None:
            return abort(404)
        return render_template('accounts/user_info.html')
    except NotFoundError:
        abort(404)


@accounts_blueprint.route("/user/<int:user_id>/change_username", methods=["POST"])
@login_required
def change_username(user_id: int):
    if request.method == 'POST':
        request_username = request.form['username']
        try:
            user = find_user_by_id(user_id)
            if not find_user_by_username(username=request_username):
                user.username = request_username
                db.session.commit()
            else:
                flash('Пользователь с таким username уже существует')
        except TypeError as e:
            db.session.rollback()
    return redirect(url_for('accounts.user_info', user_id=user_id))


@accounts_blueprint.route("/user/<int:user_id>/change_password", methods=["POST"])
@login_required
def change_password(user_id: int):
    if request.method == 'POST':
        request_password = request.form['password']
        try:
            user = find_user_by_id(user_id)
            user.hashed_password = generate_password_hash(password=request_password)
            db.session.commit()
        except Exception as e:
            flash(e)
            db.session.rollback()
    return redirect(url_for('accounts.user_info', user_id=user_id))


@accounts_blueprint.route("/user/<int:user_id>/change_city", methods=["POST"])
@login_required
def change_city(user_id: int):
    if request.method == 'POST':
        request_city = request.form['city']
        try:
            user = find_user_by_id(user_id)
            user.city = request_city
            db.session.commit()
        except TypeError as e:
            db.session.rollback()
    return redirect(url_for('accounts.user_info', user_id=user_id))


@accounts_blueprint.route("/all_users", methods=["GET"])
@login_required
def all_users():
    lst = db.engine.execute(
        'SELECT * FROM users WHERE username LIKE %(value)s;', {'value': '%'}
    ).fetchall()
    print([el[0] for el in lst])
    return render_template('accounts/all_users.html',
                           lst=lst)


@login_manager.unauthorized_handler
def unauthorized_callback():
    return redirect(url_for('accounts.login'))

accounts/templates/accounts/Oops!.html
{% extends 'base authentication.html' %}
{% block tittle %}Восстановление пароля{% endblock %}
{% block head %}
    <h1>Ooops! Вы не помните пароль? Какая жалость</h1>
    <h2>Заполните эту форму</h2>
    <h3>Вы сможете зайти в аккаунт и поменять пароль</h3>
{% endblock %}

{% block css %}padding: 10px 25px;{% endblock %}

{% block body %}
    {% with messages = get_flashed_messages() %}
        {% if messages %}
            <div class="notification is-danger" style="font-size: 20px; position:relative; top: -15px; color: #b60000; font-weight: bold">
                {{ messages[0] }}
            </div>
        {% endif %}
    {% endwith %}
    {{ form.hidden_tag() }}
    <div class="form-group">
        <input type="number" class="form-control" id="id" placeholder="id" name="id">
        <i class="fa fa-id-badge"></i>
    </div>
    <div class="form-group">
        <input type="text" class="form-control" id="username" placeholder="Username" name="username" pattern="\w{1,255}"
               title="English pls и длина от 1 до 255 символов">
        <i class="fa fa-user"></i>
    </div>
    <div class="form-group">
        <input type="text" class="form-control" id="city" placeholder="City" name="city" pattern="[а-яА-Я]{1,255}"
               title="На русском название города, длина которого от 1 до 255 символов">
        <i class="fa fa-home"></i>
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-default">ВХОД</button>
    </div>
{% endblock %}

accounts/templates/accounts/all_users.html
{% extends 'base.html' %}

{% block header %}
    <h1>{% block title %}Все пользователи{% endblock %}</h1>
{% endblock %}

{% block accounts_name %}{{ current_user.username }}{% endblock %}

{% block accounts_username %}
    <a class="nav-link active" aria-current="page" href="{{ url_for('accounts.user_info', user_id=user.id) }}">Об
        аккаунте</a>
{% endblock %}


{% block content %}
    <style>
        section {
            margin-left: auto;
            margin-right: auto;
            width: 35%;
        }

        .all_users {
            text-align: left;
            width: 35%;
            height: 100%;
            position: absolute;
            overflow: auto;
        }
    </style>
    <ul class="all_users">
        {% for user in lst %}
            <li><a href="{{ url_for('accounts.user_info', user_id=user[0]) }}" style="color: black">{{ user[1] }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base authentication.html' %}

{% block tittle %}{% block head %}Авторизация{% endblock %}{% endblock %}

{% block css %}padding: 10px 25px;{% endblock %}

{% block body %}
    {% with messages = get_flashed_messages() %}
        {% if messages %}
            <div class="notification is-danger" style="font-size: 20px; position:relative; top: -15px; color: #b60000; font-weight: bold">
                {{ messages[0] }}
            </div>
        {% endif %}
    {% endwith %}
    {{ form.hidden_tag() }}
    <div class="form-group">
        <input type="text" class="form-control" id="username" placeholder="Username" name="username" pattern="\w{0,64}" value="">
        <i class="fa fa-user"></i>
    </div>
    <div class="form-group help">
        <input type="password" class="form-control" id="password" placeholder="Password" name="password"
               pattern="\w{0,255}">
        <i class="fa fa-lock"></i>
        <a href="{{ url_for('accounts.oops') }}" class="fa fa-question-circle"></a>
    </div>
    <div class="form-group">
        <div class="main-checkbox">
            <input type="checkbox" value="none" id="remember_me" name="remember_me"/>
            <label for="remember_me"></label>
        </div>
        <span class="text">Запомнить</span>
        <button type="submit" class="btn btn-default">ВХОД</button>
    </div>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base authentication.html' %}

{% block tittle %}{% block head %}Регистрация{% endblock %}{% endblock %}

{% block css %} padding: 10px 60px; left: 35%; position: absolute;{% endblock %}

{% block body %}
    {% with messages = get_flashed_messages() %}
        {% if messages %}
            <div class="notification is-danger"
                 style="font-size: 20px; position:relative; top: -15px; color: #b60000; font-weight: bold">
                <p>{{ messages[0] }}.</p>
                <p>
                    Вы можете <a href="{{ url_for('accounts.login') }}" style="display: inline-block; color: #00009a">авторизоваться</a>
                </p>
            </div>
        {% endif %}
    {% endwith %}
    <body class="form" onload="body_onload();">
    {{ form.hidden_tag() }}
    <div class="form-group">
        <input type="text" class="form-control" id="username" placeholder="Username" name="username" value=""
               pattern="\w{0,255}" required title="Username длиной от 1 до 255 символов на English">
        <i class="fa fa-user"></i>
    </div>
    <div class="form-group">
        <input type="text" class="form-control" id="city" placeholder="city" name="city" pattern="[а-яА-Я]{1,50}" value=""
               required title="Название города на русском, длина от 1 до 255 букв">
        <i class="fa fa-home"></i>
    </div>
    <div class="form-group">
        <input type="password" class="form-control" id="password" placeholder="Password" name="password" value=""
               pattern="\w{0,255}" required title="Пароль состоит из любых символов, длиной от 1 до 255 символов">
        <i class="fa fa-lock"></i>
    </div>
    <div class="form-group">
        <input type="password" class="form-control" id="repeat_password" placeholder="Repeat password" value=""
               name="repeat_password" pattern="\w{0,255}" title="Пароль состоит из любых символов, длиной от 1 до 255 символов" required>
        <i class="fa fa-lock"></i>
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-default">Регистрация</button>
    </div>
    <script>
        window.addEventListener('DOMContentLoaded', function () {
            var form = document.querySelector('.form'),
                pas = form.querySelectorAll('#password, #repeat_password');
            form.addEventListener('submit', function (e) {
                var err = !(pas[0].value && (pas[0].value === pas[1].value))
                pas[1].setAttribute("title", err ? 'err' : '');
                err && e.preventDefault();
            }, false);
            pas[1].addEventListener('input', function (e) {
                var err = !(pas[0].value === pas[1].value)
                pas[1].setAttribute("title", err ? 'err' : 'SKHGXDL');
            }, false);
        });
    </script>
    <style type="text/css">
        [title="err"] {
            border: solid 2px red;
        }

    </style>
    </body>
{% endblock %}

accounts/templates/accounts/user_info.html
{% extends 'base.html' %}

{% block header %}
    <h1>{% block title %}Что я о тебе знаю{% endblock %}
        <img src="{{ url_for('static', filename='accounts/123.gif') }}" alt=""></h1>
{% endblock %}

{% block accounts_name %}{{ current_user.username }}{% endblock %}

{% block accounts_username %}
    <a class="nav-link active" aria-current="page" href="{{ url_for('accounts.user_info', user_id=current_user.id) }}">Об
        аккаунте</a>
{% endblock %}

{% block content %}
    <script type="text/javascript">
        $(document).ready(function () {
            $(".one").click(function () {
                $("#panelsStayOpen-collapseOne").collapse('toggle');
            });
            $(".two").click(function () {
                $("#panelsStayOpen-collapseTwo").collapse('toggle');
            });
            $(".three").click(function () {
                $("#panelsStayOpen-collapseThree").collapse('toggle');
            });
            $(".four").click(function () {
                $("#panelsStayOpen-collapseFour").collapse('toggle');
            });
        });
    </script>
    <style>
        .accordion {
            width: 60%;
            margin-left: auto;
            margin-right: auto;
        }

        .accordion-button {
            font-size: 2rem;
            font-weight: bold;
        }

        .accordion-body {
            font-size: 25px;
        }
    </style>
    <link rel="stylesheet" href="{{ url_for('static', filename='style_auth.css') }}">
    {% with messages = get_flashed_messages() %}
        {% if messages %}
            <div class="notification is-danger" style="font-size: 30px; position:relative; top: -15px; color: red; font-weight: bold">
            <img src="{{ url_for('static', filename='accounts/warning.png') }}" alt="">
                {{ messages[0] }}
            <img src="{{ url_for('static', filename='accounts/warning.png') }}" alt="">
            </div>
        {% endif %}
    {% endwith %}
    <div class="accordion" id="accordionPanelsStayOpenExample">
        <div class="accordion-item">
            <h2 class="accordion-header" id="panelsStayOpen-headingOne">
                <button class="accordion-button collapsed one" type="button" data-bs-toggle="collapse"
                        data-bs-target="#panelsStayOpen-collapseOne" aria-expanded="false"
                        aria-controls="panelsStayOpen-collapseOne">
                    ID: {{ current_user.id }}
                </button>
            </h2>
            <div id="panelsStayOpen-collapseOne" class="accordion-collapse collapse"
                 aria-labelledby="panelsStayOpen-headingOne">
                <div class="accordion-body">
                    Меня менять нельзя 🙁
                </div>
            </div>
        </div>
        <div class="accordion-item">
            <h2 class="accordion-header" id="panelsStayOpen-headingTwo">
                <button class="accordion-button collapsed two" type="button" data-bs-toggle="collapse"
                        data-bs-target="#panelsStayOpen-collapseTwo" aria-expanded="false"
                        aria-controls="panelsStayOpen-collapseTwo">
                    Username: {{ current_user.username }}
                </button>
            </h2>
            <div id="panelsStayOpen-collapseTwo" class="accordion-collapse collapse"
                 aria-labelledby="panelsStayOpen-headingTwo">
                <div class="accordion-body">
                    Если вы хотите поменять username, введите новый ниже
                    <form method="POST" class="form-horizontal"
                          action="{{ url_for('accounts.change_username', user_id=current_user.id) }}"
                          style="padding-bottom: 0px;">
                        <div class="form-group" style="display:inline-block;">
                            <input type="text" class="form-control" id="username" placeholder="Username" name="username"
                                   pattern="\w{0,64}">
                            <i class="fa fa-user"></i>
                        </div>
                        <button type="submit" class="btn btn-default">изменить</button>
                    </form>
                </div>
            </div>
        </div>
        <div class="accordion-item">
            <h2 class="accordion-header" id="panelsStayOpen-headingThree">
                <button class="accordion-button collapsed three" type="button" data-bs-toggle="collapse"
                        data-bs-target="#panelsStayOpen-collapseThree" aria-expanded="false"
                        aria-controls="panelsStayOpen-collapseThree">
                    Пароль: меня отобразить нельзя 🙁
                </button>
            </h2>
            <div id="panelsStayOpen-collapseThree" class="accordion-collapse collapse"
                 aria-labelledby="panelsStayOpen-headingThree">
                <div class="accordion-body">
                    Если вы хотите поменять пароль, введите новый ниже
                    <form method="POST" class="form-horizontal"
                          action="{{ url_for('accounts.change_password', user_id=current_user.id) }}"
                          style="padding-bottom: 0px;">
                        <div class="form-group" style="display:inline-block;">
                            <input type="password" class="form-control" id="password" placeholder="Password"
                                   name="password"
                                   pattern="\w{0,64}">
                            <i class="fa fa-lock"></i>
                        </div>
                        <button type="submit" class="btn btn-default">изменить</button>
                    </form>
                </div>
            </div>
        </div>
        <div class="accordion-item">
            <h2 class="accordion-header" id="panelsStayOpen-headingFour">
                <button class="accordion-button collapsed four" type="button" data-bs-toggle="collapse"
                        data-bs-target="#panelsStayOpen-collapseFour" aria-expanded="false"
                        aria-controls="panelsStayOpen-collapseFour">
                    Город: {{ current_user.city }}
                </button>
            </h2>
            <div id="panelsStayOpen-collapseFour" class="accordion-collapse collapse"
                 aria-labelledby="panelsStayOpen-headingFour">
                <div class="accordion-body">
                    Если вы хотите поменять город, введите новый ниже
                    <form method="POST" class="form-horizontal"
                          action="{{ url_for('accounts.change_city', user_id=current_user.id) }}" style="padding-bottom: 0px;">
                        <div class="form-group" style="display:inline-block;">
                            <input type="text" class="form-control" id="city" placeholder="City" name="city">
                            <i class="fa fa-home"></i>
                        </div>
                        <button type="submit" class="btn btn-default">изменить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}