accounts/controllers.py
from flask import request, redirect, url_for, flash, render_template, Blueprint, abort
from flask_login import login_user, login_required, logout_user, current_user
from werkzeug.security import generate_password_hash

from accounts.forms import RegistrationForm, LoginForm, LoginFormWithoutPassword
from accounts.login_manager import login_manager
from accounts.models import User
from accounts.services import find_by_username_and_password, NotFoundError, find_user_by_id, \
    find_user_by_username, find_by_id_username_city
from project_dataase.database import db

accounts_blueprint = Blueprint('accounts', __name__, template_folder='templates')


@accounts_blueprint.route('/register', methods=('POST', 'GET'))
def register():
    form: RegistrationForm = RegistrationForm(request.form)
    if request.method == 'POST':
        if form.validate_on_submit():
            try:
                if find_user_by_username(form.username.data):
                    flash('Аккаунт с таким Username уже существует')
                    return redirect(url_for('accounts.register'))
                user = User(username=form.username.data, hashed_password=generate_password_hash(form.password.data),
                            city=form.city.data, role='0')
                db.session.add(user)
                db.session.commit()
                login_user(user, remember=False)
                return redirect(url_for('company_management.main_page'))
            except TypeError as e:
                db.session.rollback()
                print('Ошибка добавления в БД')
        else:
            flash("Упс, ты не прошёл валидацию")
    return render_template('accounts/signup.html', form=form)


@accounts_blueprint.route('/login', methods=('GET', 'POST'))
def login():
    form: LoginForm = LoginForm(request.form)
    if request.method == 'POST' and form.validate_on_submit():
        try:
            user: User = find_by_username_and_password(form.username.data, form.password.data)
        except Exception as e:
            flash(str(e) or 'Unknown error')
            # save_username = form.username.data
            return redirect(url_for('accounts.login'))
        else:
            login_user(user, remember=form.remember_me.data)
            return redirect(url_for('company_management.main_page'))
    return render_template('accounts/login.html', form=form)


@accounts_blueprint.route("/oops", methods=["GET", "POST"])
def oops():
    form: LoginFormWithoutPassword = LoginFormWithoutPassword(request.form)
    if request.method == 'POST' and form.validate_on_submit():
        request_id: int = int(request.form['id'])
        request_username: str = request.form['username']
        request_city: str = request.form['city']
        try:
            user = find_by_id_username_city(user_id=form.id.data, username=form.username.data, city=form.city.data)
        except Exception as e:
            flash(str(e) or 'Unknown error')
            return redirect(url_for('accounts.oops'))
        else:
            login_user(user)
            return redirect(url_for('company_management.main_page'))
    return render_template('accounts/Oops!.html', form=form)


@accounts_blueprint.route("/logout", methods=["GET"])
@login_required
def logout():
    logout_user()
    return redirect(url_for('company_management.main_page'))


@accounts_blueprint.route("/user/<int:user_id>", methods=["GET", "POST"])
@login_required
def user_info(user_id: int):
    try:
        user: object = find_user_by_id(user_id)
        if user is None:
            return abort(404)
        return render_template('accounts/user_info.html')
    except NotFoundError:
        abort(404)


@accounts_blueprint.route("/user/<int:user_id>/change_username", methods=["POST"])
@login_required
def change_username(user_id: int):
    if request.method == 'POST':
        request_username = request.form['username']
        try:
            user = find_user_by_id(user_id)
            if not find_user_by_username(username=request_username):
                user.username = request_username
                db.session.commit()
            else:
                flash('Пользователь с таким username уже существует')
        except TypeError as e:
            db.session.rollback()
    return redirect(url_for('accounts.user_info', user_id=user_id))


@accounts_blueprint.route("/user/<int:user_id>/change_password", methods=["POST"])
@login_required
def change_password(user_id: int):
    if request.method == 'POST':
        request_password = request.form['password']
        try:
            user = find_user_by_id(user_id)
            user.hashed_password = generate_password_hash(password=request_password)
            db.session.commit()
        except Exception as e:
            flash(e)
            db.session.rollback()
    return redirect(url_for('accounts.user_info', user_id=user_id))


@accounts_blueprint.route("/user/<int:user_id>/change_city", methods=["POST"])
@login_required
def change_city(user_id: int):
    if request.method == 'POST':
        request_city = request.form['city']
        try:
            user = find_user_by_id(user_id)
            user.city = request_city
            db.session.commit()
        except TypeError as e:
            db.session.rollback()
    return redirect(url_for('accounts.user_info', user_id=user_id))


@accounts_blueprint.route("/all_users", methods=["GET"])
@login_required
def all_users():
    lst = db.engine.execute(
        'SELECT * FROM users WHERE username LIKE %(value)s;', {'value': '%'}
    ).fetchall()
    print([el[0] for el in lst])
    return render_template('accounts/all_users.html',
                           lst=lst)


@login_manager.unauthorized_handler
def unauthorized_callback():
    return redirect(url_for('accounts.login'))

company_management/controllers.py
import json

from flask import Blueprint, render_template, request, flash, redirect, url_for
from flask_login import current_user, login_required

from accounts.models import Favorite
from accounts.services import find_user_by_id
from company_management.api import visual_crossing_weather, open_weather_map
from company_management.forms import FeedBack
from company_management.models import City
from company_management.parse import gismeteo
from project_dataase.database import db

company_management_blueprint = Blueprint('company_management', __name__, template_folder='templates')


@company_management_blueprint.route('/', methods=('GET', 'POST'))
def main_page():
    city = 'Москва'
    l_city: str = 'https://www.gismeteo.ru/weather-moscow-4368/10-days/'
    sql = City.query.all()
    dictionary = {}
    for user in sql:
        dictionary[user.name] = user.link_city
    if request.method == 'POST':
        city = request.form['city']
        f_city: City = City.query.filter_by(name=city).first()
        l_city = f_city.link_city
    else:
        f_city: City = City.query.filter_by(name=city).first()
    if current_user.is_authenticated:
        user = find_user_by_id(current_user.id)
        if Favorite.query.filter_by(city_id=City.query.filter_by(name=city).first().id,
                                    user_id=current_user.id).first():
            check_city = True
        else:
            check_city = False
        return render_template('company_management/main_page.html', city=city,
                               dictionary=json.dumps(dictionary), massiv=list(gismeteo(l_city).items()),
                               f_city=f_city.id, check_city=check_city, api_1=visual_crossing_weather(city),
                               api_2=open_weather_map(city))

    return render_template('company_management/main_page.html', city=city, dictionary=json.dumps(dictionary),
                           massiv=list(gismeteo(l_city).items()), f_city=f_city.id, api_1=visual_crossing_weather(city),
                           api_2=open_weather_map(city))


@company_management_blueprint.route('/info', methods=["GET"])
def info():
    # if current_user.is_authenticated:
    #     return render_template('company_management/info.html', user=find_user_by_id(current_user.id))
    return render_template('company_management/info.html')


@company_management_blueprint.route('/review', methods=["GET", "POST"])
@login_required
def review() -> object:
    form: FeedBack = FeedBack(request.form)
    if request.method == "POST":
        if form.validate_on_submit():
            flash('Ваш отзыв отправлен! Спасибо за обратную связь!')
            return redirect(url_for('company_management.review'))
        else:
            flash('Ваши поле(я) не прошли валидацию')
            return redirect(url_for('company_management.review'))
    return render_template('company_management/review.html', form=form)


@company_management_blueprint.route('/favorite', methods=["GET"])
@login_required
def favorite() -> object:
    lst_favorite_object: object = Favorite.query.filter_by(user_id=current_user.id).all()
    lst_city_id = [x.city_id for x in lst_favorite_object]
    lst_city_object: list[City] = []
    for city_id in lst_city_id:
        lst_city_object.append(City.query.filter_by(id=city_id).first())
    return render_template('company_management/favorite.html',
                           lst=lst_city_object)


@company_management_blueprint.route('/favorite/delete_favorite_from_favorite/<int:f_city>')
@login_required
def delete_favorite_from_favorite(f_city: int):
    try:
        Favorite.query.filter_by(user_id=current_user.id, city_id=f_city).delete()
        db.session.commit()
    except TypeError as e:
        flash('Ошибка добавления в БД')
    return redirect(url_for('company_management.favorite'))


@company_management_blueprint.route('/change_favorite/<int:f_city>')
@login_required
def add_favorite(f_city: int):
    try:
        favorite_city: Favorite = Favorite(user_id=current_user.id, city_id=f_city)
        db.session.add(favorite_city)
        db.session.commit()
    except TypeError as e:
        db.session.rollback()
        flash('Ошибка добавления в БД')
    return redirect(url_for('company_management.main_page'))


@company_management_blueprint.route('/delete_favorite/<int:f_city>')
@login_required
def delete_favorite(f_city: int):
    try:
        Favorite.query.filter_by(user_id=current_user.id, city_id=f_city).delete()
        db.session.commit()
    except TypeError as e:
        flash('Ошибка добавления в БД')
    return redirect(url_for('company_management.main_page'))

templates/base authentication.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"/>
    <link rel="stylesheet" href="{{ url_for('static', filename='style_base.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='style_auth.css') }}">
    <link rel="shortcut icon" href="{{ url_for('static', filename='pic/cloudy.svg') }}" type="image/x-icon">
    <title>{% block tittle %}{% endblock %}</title>
    <style>
        .form-horizontal .btn {
            float: right;
            font-size: 14px;
            color: #fff;
            background: #00b4ef;
        {% block css %}
        {% endblock %}
            border-radius: 30px;
            border: none;
            text-transform: capitalize;
            transition: all 0.5s ease 0s;
        }
    </style>
    <ul class="nav" style="display: inline-block; left: 15%; position:relative;">
        <li class="nav-item">
            <a class="nav-link active" aria-current="page"
               href="{{ url_for('company_management.main_page') }}">Weather</a>
            <img src="{{ url_for('static', filename='pic/cloudy.svg') }}" alt="cloud"
                 style="position: relative;
                        width: 86px;
                        height: 83px;
                        left: -33%;
                        top: -83%;">
        </li>
    </ul>
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-md-offset-3 col-md-6">
            <form class="form-horizontal" method="post">
                <span class="heading">{% block head %}{% endblock %}</span>
                {% block body %}{% endblock %}
            </form>
        </div>
    </div>
</div>
</body>
</html>

templates/base.html
<!doctype html>
<title>{% block title %}{% endblock %}</title>
<link rel="stylesheet" href="{{ url_for('static', filename='style_base.css') }}">
<link rel="shortcut icon" href="{{ url_for('static', filename='pic/cloudy.svg') }}" type="image/x-icon">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

<body style="text-align: center">
<header>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-beta.2/css/bootstrap.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-beta.2/js/bootstrap.bundle.min.js"></script>
    <script src="https://stacksnippets.net/scripts/snippet-javascript-console.min.js?v=1"></script>
    <ul class="nav" style="display: inline-block">
        <li class="nav-item">
            <a class="nav-link active" aria-current="page"
               href="{{ url_for('company_management.main_page') }}">Weather</a>
            <img src="{{ url_for('static', filename='pic/cloudy.svg') }}" alt="cloud"
                 style="position: relative;
                        width: 86px;
                        height: 83px;
                        left: -65%;
                        top: -83%;">
        </li>
        {% block search %}
        {% endblock %}
        <li class="nav-item-1">
            <a class="nav-link active" aria-current="page"
               href="{{ url_for('company_management.favorite') }}">Избранное</a>
            <img src="{{ url_for('static', filename='pic/star.svg') }}" alt="star"
                 style="position: relative;
                        width: 50px;
                        height: 48px;
                        left: -50%;
                        top: -57px;">
        </li>
        <li class="nav-item-2">
            <div class="dropdown">
                <button class="nav-link active btn btn-default" type="button" id="dropdownMenuButton1"
                        data-toggle="dropdown" style="font-weight: 600; font-size: 36px; line-height: 44px;">
                    {% if not current_user.is_authenticated %}
                        Войти
                    {% else %}
                        {{ current_user.username }}
                    {% endif %}
                    <span class="caret"></span>
                </button>
                <ul class="dropdown-menu">
                    {% if not current_user.is_authenticated %}
                        <a class="nav-link active" aria-current="page" href="{{ url_for('accounts.login') }}">Авторизоваться</a>
                        <a class="nav-link active" aria-current="page" href="{{ url_for('accounts.register') }}">Регистрация</a>
                    {% endif %}
                    {% if current_user.is_authenticated %}
                        <a class="nav-link active" aria-current="page"
                           href="{{ url_for('accounts.logout') }}">Выйти</a>
                        <a class="nav-link active" aria-current="page"
                           href="{{ url_for('accounts.user_info', user_id=current_user.id) }}">Об аккаунте</a>
                        {% if current_user.role == 1 %}
                            <a class="nav-link active" aria-current="page" href="{{ url_for('accounts.all_users') }}">Пользователи</a>
                        {% endif %}
                    {% endif %}
                    <a class="nav-link active" aria-current="page" href="{{ url_for('company_management.info') }}">О
                        сайте</a>
                    <a class="nav-link active" aria-current="page" href="{{ url_for('company_management.review') }}">Оставить
                        отзыв</a>
                </ul>
                <img src="{{ url_for('static', filename='pic/user.svg') }}" alt="User"
                     style="position: relative;
                        width: 67px;
                        height: 52px;
                        left: -67%;
                        top: -60px">
            </div>
        </li>
    </ul>
</header>
</body>
<section class="content">
    <header>
        {% block header %}{% endblock %}
    </header>
    {% block content %}{% endblock %}
</section>