company_management/models.py
from flask_login import UserMixin

from project_dataase.database import db


class City(UserMixin, db.Model):
    __tablename__ = "city"

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64), index=True, unique=True, nullable=False)
    link_city = db.Column(db.String(1000), unique=False, nullable=False)

    def __repr__(self):
        return f"<User {self.name}>"

company_management/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, validators


class FeedBack(FlaskForm):
    name = StringField('name', [
        validators.Length(min=1, max=255),
        validators.DataRequired()
    ])
    email = StringField('email', [validators.DataRequired(),
                                  validators.Length(min=1, max=255)
                                  ])
    message = StringField('message', [
        validators.Length(min=1, max=10000),
        validators.DataRequired()
    ])

company_management/__init__.py
from flask import Blueprint

company_management_blueprint = Blueprint('company_management', __name__)

company_management/controllers.py
import json

from flask import Blueprint, render_template, request, flash, redirect, url_for
from flask_login import current_user, login_required

from accounts.models import Favorite
from accounts.services import find_user_by_id
from company_management.api import visual_crossing_weather, open_weather_map
from company_management.forms import FeedBack
from company_management.models import City
from company_management.parse import gismeteo
from project_dataase.database import db

company_management_blueprint = Blueprint('company_management', __name__, template_folder='templates')


@company_management_blueprint.route('/', methods=('GET', 'POST'))
def main_page():
    city = 'Москва'
    l_city: str = 'https://www.gismeteo.ru/weather-moscow-4368/10-days/'
    sql = City.query.all()
    dictionary = {}
    for user in sql:
        dictionary[user.name] = user.link_city
    if request.method == 'POST':
        city = request.form['city']
        f_city: City = City.query.filter_by(name=city).first()
        l_city = f_city.link_city
    else:
        f_city: City = City.query.filter_by(name=city).first()
    if current_user.is_authenticated:
        user = find_user_by_id(current_user.id)
        if Favorite.query.filter_by(city_id=City.query.filter_by(name=city).first().id,
                                    user_id=current_user.id).first():
            check_city = True
        else:
            check_city = False
        return render_template('company_management/main_page.html', city=city,
                               dictionary=json.dumps(dictionary), massiv=list(gismeteo(l_city).items()),
                               f_city=f_city.id, check_city=check_city, api_1=visual_crossing_weather(city),
                               api_2=open_weather_map(city))

    return render_template('company_management/main_page.html', city=city, dictionary=json.dumps(dictionary),
                           massiv=list(gismeteo(l_city).items()), f_city=f_city.id, api_1=visual_crossing_weather(city),
                           api_2=open_weather_map(city))


@company_management_blueprint.route('/info', methods=["GET"])
def info():
    # if current_user.is_authenticated:
    #     return render_template('company_management/info.html', user=find_user_by_id(current_user.id))
    return render_template('company_management/info.html')


@company_management_blueprint.route('/review', methods=["GET", "POST"])
@login_required
def review() -> object:
    form: FeedBack = FeedBack(request.form)
    if request.method == "POST":
        if form.validate_on_submit():
            flash('Ваш отзыв отправлен! Спасибо за обратную связь!')
            return redirect(url_for('company_management.review'))
        else:
            flash('Ваши поле(я) не прошли валидацию')
            return redirect(url_for('company_management.review'))
    return render_template('company_management/review.html', form=form)


@company_management_blueprint.route('/favorite', methods=["GET"])
@login_required
def favorite() -> object:
    lst_favorite_object: object = Favorite.query.filter_by(user_id=current_user.id).all()
    lst_city_id = [x.city_id for x in lst_favorite_object]
    lst_city_object: list[City] = []
    for city_id in lst_city_id:
        lst_city_object.append(City.query.filter_by(id=city_id).first())
    return render_template('company_management/favorite.html',
                           lst=lst_city_object)


@company_management_blueprint.route('/favorite/delete_favorite_from_favorite/<int:f_city>')
@login_required
def delete_favorite_from_favorite(f_city: int):
    try:
        Favorite.query.filter_by(user_id=current_user.id, city_id=f_city).delete()
        db.session.commit()
    except TypeError as e:
        flash('Ошибка добавления в БД')
    return redirect(url_for('company_management.favorite'))


@company_management_blueprint.route('/change_favorite/<int:f_city>')
@login_required
def add_favorite(f_city: int):
    try:
        favorite_city: Favorite = Favorite(user_id=current_user.id, city_id=f_city)
        db.session.add(favorite_city)
        db.session.commit()
    except TypeError as e:
        db.session.rollback()
        flash('Ошибка добавления в БД')
    return redirect(url_for('company_management.main_page'))


@company_management_blueprint.route('/delete_favorite/<int:f_city>')
@login_required
def delete_favorite(f_city: int):
    try:
        Favorite.query.filter_by(user_id=current_user.id, city_id=f_city).delete()
        db.session.commit()
    except TypeError as e:
        flash('Ошибка добавления в БД')
    return redirect(url_for('company_management.main_page'))

company_management/templates/company_management/favorite.html
{% extends 'base.html' %}

{% block title %}Избранное{% endblock %}

{% block header %}
    <style>
        .shadow-lg.p-3.mb-5.bg-body {
            width: 60%;
            margin-left: auto;
            margin-right: auto;
            border-radius: 3em;
            font-size: 40px;
            text-align: left;
            font-weight: bold;
        }

        .shadow-lg.p-3.mb-5.bg-body.p {
            position: relative;
            left: 5%;
        }

        .btn-close {
            display: inline-block;
            right: 22%;
            position: absolute;
            padding-top: 0px;
            padding-right: 0px;
            padding-left: 0px;
            padding-bottom: 0px;
            height: 76px;
            width: 61px;
        }
    </style>
    {% for x in lst %}
        <div class="shadow-lg p-3 mb-5 bg-body">
        <form method="get" action="{{ url_for('company_management.delete_favorite_from_favorite', f_city=x.id) }}">
            <p style="display: inline-block">{{ x.name }}</p>
            <button type="submit" class="btn-close" aria-label="Close">
            </button>
        </form>
        </div>
    {% endfor %}
{% endblock %}

company_management/templates/company_management/info.html
{% extends 'base.html' %}

{% block title %}О сайте{% endblock %}

{% block header %}
    <style>
        p {
            font-size: 30px;
            font-weight: bolder;
        }
    </style>
    <br><br><br>
    <h1>Привет, здесь когда-нибудь (нет) будет информация о сайте!</h1><br><br><br>
    <p>Это агрегатор погоды, здесь ты можешь узнать погоду в своём городе сразу из нескольких источников</p>
{% endblock %}

company_management/templates/company_management/review.html
{% extends 'base.html' %}

{% block title %}Оставить отзыв{% endblock %}

{% block header %}
    {% with messages = get_flashed_messages() %}
        {% if messages %}
            <div class="notification is-danger"
                 style="font-size: 20px; position:relative; top: -15px; color: #b60000; font-weight: bold">
                {{ messages[0] }}
            </div>
        {% endif %}
    {% endwith %}
    <div class="card mx-auto mb-4 rounded-0" style="max-width: 35rem;">
        <div class="card-body position-relative">
            <!-- Форма обратной связи -->
            <form id="feedbackForm" method="POST">
                {{ form.csrf_token }}
                <div class="form-row">
                    <div class="col-sm-6">
                        <!-- Имя пользователя -->
                        <div class="form-group">
                            <label for="name" class="control-label">Имя</label>
                            <input id="name" type="text" name="name" class="form-control" value="" placeholder="Имя"
                                   minlength="1" maxlength="255" required="required">
                            <div class="invalid-feedback"></div>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <!-- Email пользователя -->
                        <div class="form-group">
                            <label for="email" class="control-label">Email-адрес</label>
                            <input id="email" type="email" name="email" required="required" class="form-control" minlength="5" maxlength="255"
                                   value="" placeholder="Email-адрес">
                            <div class="invalid-feedback"></div>
                        </div>
                    </div>
                </div>
                <!-- Сообщение пользователя -->
                <div class="form-group">
                    <label for="message" class="control-label">Сообщение</label>
                    <textarea id="message" name="message" class="form-control" rows="3"
                              placeholder="Сообщение" minlength="1"
                              maxlength="10000" required="required"></textarea>
                    <div class="invalid-feedback"></div>
                </div>
                <!-- Сообщение при ошибке -->
                <div class="alert alert-danger form-error d-none">
                    Исправьте данные и отправьте форму ещё раз.
                </div>
                <!-- Кнопка для отправки формы -->
                <div class="text-right submit">
                    <button type="submit" class="btn btn-primary position-relative">Отправить сообщение</button>
                </div>
            </form>

            <!-- Сообщение об успешной отправки формы -->
            <div class="form-result-success d-none text-center justify-content-center align-items-center" style="position: absolute;
    top: 0; left: 0; right: 0; bottom: 0; background: rgba(0,0,0,.6); color: #fff; font-size: 1.25rem;">
                <div class="alert alert-success rounded-0">Форма успешно отправлена. Нажмите на
                    <a class="alert-link" href="#" data-reloadform="#feedbackForm">ссылку</a>, чтобы отправить ещё одно
                    сообщение.
                </div>
            </div>

        </div>
    </div>
{% endblock %}